-- =============================================================================
-- 002_seed_initial_content.sql
-- Initial content seed: admin user, settings, pages, vehicles, services, timeline
-- Texts are revised marketing copy; vehicle technical specs are UNCHANGED.
-- =============================================================================

-- ── Admin user (Username: admin / Passwort: ChangeMe!2026 – nach Login aendern!) ──
INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2y$12$nb4I2ezICU4Y1IAbGxuXgO3e6oWF//UdykBQmD6ekJfoyzjRUi98S', 'admin');

-- ── Sitewide settings ────────────────────────────────────────────────────────
INSERT INTO settings (key, value) VALUES
  ('company_name',             'Rothe-Transporte und Speditions GbR'),
  ('owners',                   'Karl-Otto Rothe & Christopher Rothe'),
  ('address_street',           'Aeckerlesweg 3'),
  ('address_zip',              '72141'),
  ('address_city',             'Walddorfhaeslach'),
  ('address_country',          'Deutschland'),
  ('phone',                    '07127 18231'),
  ('phone_e164',               '+497127182310'),
  ('email',                    'info@rothe-transporte.de'),
  ('founded_year',             '1978'),
  ('geo_lat',                  '48.5306'),
  ('geo_lng',                  '9.1564'),
  ('opening_hours',            'Mo-Fr 07:00-17:00'),
  ('opening_hours_schema',     'Mo-Fr 07:00-17:00'),
  ('areas_served',             'DE, AT, CH, FR, NL, BE'),
  ('meta_default_title',       'Rothe-Transporte – Maschinen- und Spezialtransporte | Walddorfhaeslach'),
  ('meta_default_description', 'Familienspedition seit 1978 in Walddorfhaeslach. Maschinentransporte, Tieflader, Tautliner, Lagerung. Touren in DE, AT, CH, FR, NL, BE. Anrufen: 07127 18231.'),
  ('og_default_image_id',      ''),
  ('hero_image_id',            ''),
  ('owner_quote',              'Wir bewegen Maschinen seit 1978 – mit eigenem Fuhrpark, festen Fahrern und kurzen Wegen. Das ist kein Versprechen, das ist Alltag.'),
  ('owner_quote_attribution',  'Karl-Otto & Christopher Rothe');

-- ── Pages ─────────────────────────────────────────────────────────────────────
INSERT INTO pages (slug, title, meta_title, meta_description, hero_headline, hero_sub, content_html, sort_order) VALUES
('home',
 'Startseite',
 'Rothe-Transporte – Maschinen- und Spezialtransporte | Walddorfhaeslach',
 'Familienspedition seit 1978. Maschinentransporte, Tieflader bis 28 t, Tautliner, eigene Lager. Touren in DE, AT, CH, FR, NL, BE. Anrufen: 07127 18231.',
 'Schweres bewegen. Leise. Pünktlich. Seit zwei Generationen.',
 'Tieflader, Tautliner und Spezialanhänger – aus Walddorfhaeslach in sechs Länder Europas.',
 '<p>Wir sind Rothe-Transporte: ein Familienunternehmen aus Walddorfhaeslach mit eigenem Fuhrpark und über vier Jahrzehnten Erfahrung im Maschinen- und Spezialtransport. Unsere Disposition kennt jede Tour persönlich, unsere Fahrer kennen ihre Fahrzeuge.</p><h2>Was uns auszeichnet</h2><p>Termintreue, klare Kommunikation und eine Flotte, die für sperrige Maschinen, voluminöse Anlagen und palettierte Ware gleichermaßen gerüstet ist. Wir laden in Deutschland, wir entladen in Österreich, der Schweiz, Frankreich, den Niederlanden und Belgien – und wenn nötig, auch dazwischen.</p>',
 1),
('ueber-uns',
 'Über uns',
 'Über uns – Familienspedition seit 1978 | Rothe-Transporte',
 'Karl-Otto und Christopher Rothe führen die Spedition in zweiter Generation. Vom Ein-Mann-Betrieb 1978 zum spezialisierten Maschinentransporteur mit eigenem Fuhrpark.',
 'Familienbetrieb seit 1978. Heute in zweiter Generation.',
 'Aus einem Ein-Mann-Betrieb in Münsingen wurde eine spezialisierte Spedition mit Sitz in Walddorfhaeslach.',
 '<h2>Unsere Geschichte</h2><p>Karl-Otto Rothe gründete die Firma 1978 in Münsingen. 1985 zog der Betrieb nach Walddorfhaeslach um. Was als Ein-Mann-Betrieb begann, ist heute eine spezialisierte Spedition für Maschinen- und Spezialtransporte. Seit 2010 führt Christopher Rothe das Unternehmen in zweiter Generation mit.</p><h2>Was uns leitet</h2><p>Wir liefern, was wir zusagen. Punktgenau, sorgfältig verzurrt, mit denselben Fahrern, die unsere Kunden seit Jahren kennen. Seit 2018 sind wir anerkannter Ausbildungsbetrieb – weil gute Logistik nur gelingt, wenn das Wissen weitergegeben wird.</p>',
 2),
('leistungen',
 'Leistungen',
 'Leistungen – Maschinentransport, Tieflader, Lagerung | Rothe-Transporte',
 'Maschinen- und Spezialtransporte, Tieflader bis 28 t, Tautliner, Lagerung in eigenen Hallen, Stapler- und Entladedienste bis 3,5 t. Sechs Länder, ein Ansprechpartner.',
 'Vier Leistungen. Ein Anspruch.',
 'Vom Maschinentransport bis zur Einlagerung – alles aus einer Hand und mit eigenem Personal.',
 '<h2>Was wir bewegen</h2><p>Maschinen, Anlagen, palettierte Industriegüter, Großteile. Wir kombinieren passendes Fahrzeug, geübte Fahrer und kurze Disposition – und wir behalten die Verantwortung für die Sendung von der Abholung bis zur Übergabe.</p><h2>Wo wir bewegen</h2><p>Regelmäßige Touren in Deutschland, Österreich, der Schweiz, Frankreich, den Niederlanden und Belgien. Tagesfahrten innerhalb des deutschsprachigen Raums sind Standard.</p>',
 3),
('fahrzeuge',
 'Fahrzeuge',
 'Fahrzeuge & Fuhrpark – Tieflader, Tautliner, Anhänger | Rothe-Transporte',
 'Unser Fuhrpark: Tieflader bis 28 t Nutzlast, Tautliner-Sattelzug bis 25 t, Anhänger mit Auffahrrampe und Motorwagen mit Ladekran. Alle technischen Daten auf einen Blick.',
 'Vier Fahrzeuge. Klar gerechnet.',
 'Maße, Nutzlast, Paletten – alles, was Disponenten wissen müssen, in einer Übersicht.',
 '<p>Unser Fuhrpark ist konsequent auf Maschinen- und Spezialtransporte ausgelegt. Jedes Fahrzeug hat seinen klaren Einsatzzweck – und seine festen Fahrer.</p>',
 4),
('karriere',
 'Karriere',
 'Karriere – Berufskraftfahrer (m/w/d) gesucht | Rothe-Transporte',
 'Familienbetrieb sucht Berufskraftfahrer für Maschinen- und Spezialtransporte in DE, AT, CH, FR, NL, BE. Moderner Fuhrpark, faire Bezahlung, kurze Wege. Bewerbung per E-Mail.',
 'Bei uns ist jeder Fahrer Stammbesatzung.',
 'Wir suchen Berufskraftfahrer (CE) für unsere Touren in sechs Länder Europas.',
 '<h2>Was wir bieten</h2><ul><li>Familienbetrieb mit kurzen Entscheidungswegen</li><li>Moderner, eigener Fuhrpark</li><li>Faire, pünktliche Bezahlung</li><li>Sicherer Arbeitsplatz mit Perspektive</li><li>Wertschätzung – kein Leiharbeiter-Karussell</li></ul><h2>Bewerbung</h2><p>Schicken Sie uns Ihre Unterlagen per E-Mail an <a href="mailto:info@rothe-transporte.de">info@rothe-transporte.de</a> oder per Post an: Rothe-Transporte und Speditions GbR, Aeckerlesweg 3, 72141 Walddorfhaeslach.</p>',
 5),
('kontakt',
 'Kontakt',
 'Kontakt – Rothe-Transporte Walddorfhaeslach | 07127 18231',
 'Rothe-Transporte und Speditions GbR, Aeckerlesweg 3, 72141 Walddorfhaeslach. Telefon: 07127 18231. E-Mail: info@rothe-transporte.de. Mo-Fr 07:00-17:00 Uhr.',
 'Direkt zur Disposition.',
 'Anrufen, schreiben, vorbeikommen – Sie erreichen uns ohne Umwege.',
 '<p>Wir nehmen Anfragen am liebsten direkt am Telefon entgegen – so klären wir Maße, Termine und Strecke in einem Gespräch.</p>',
 6),
('impressum',
 'Impressum',
 'Impressum | Rothe-Transporte',
 'Anbieterkennzeichnung gemäß § 5 TMG für rothe-transporte.de.',
 'Impressum',
 'Angaben gemäß § 5 TMG.',
 '<h2>Anbieter</h2><p>Rothe-Transporte und Speditions GbR<br>Aeckerlesweg 3<br>72141 Walddorfhaeslach<br>Deutschland</p><h2>Vertretungsberechtigte Gesellschafter</h2><p>Karl-Otto Rothe<br>Christopher Rothe</p><h2>Kontakt</h2><p>Telefon: <a href="tel:+497127182310">07127 18231</a><br>E-Mail: <a href="mailto:info@rothe-transporte.de">info@rothe-transporte.de</a></p><h2>Haftung für Inhalte</h2><p>Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.</p><h2>Haftung für Links</h2><p>Unser Angebot enthält ggf. Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen.</p><h2>Urheberrecht</h2><p>Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht.</p>',
 7),
('datenschutz',
 'Datenschutz',
 'Datenschutzerklärung | Rothe-Transporte',
 'Datenschutzerklärung gemäß DSGVO. Wir verwenden keine Cookies, kein Tracking, keine externen Skripte.',
 'Datenschutz',
 'Diese Website verwendet keine Cookies und kein Tracking.',
 '<h2>Verantwortlicher</h2><p>Rothe-Transporte und Speditions GbR<br>Aeckerlesweg 3<br>72141 Walddorfhaeslach<br>Telefon: 07127 18231<br>E-Mail: info@rothe-transporte.de</p><h2>Erhebung allgemeiner Informationen</h2><p>Wenn Sie diese Website aufrufen, werden automatisch Informationen allgemeiner Natur durch unseren Webserver erfasst (Browsertyp, Betriebssystem, Domainname, IP-Adresse, Datum, Zugriffszeit). Diese Informationen werden anonymisiert ausgewertet und ausschließlich zur Verbesserung des Angebots verwendet.</p><h2>Cookies und Tracking</h2><p>Diese Website verwendet keine Cookies, kein Tracking, kein Analyse-Tool und keine externen Skripte. Es findet keine Datenübermittlung an Dritte statt.</p><h2>Kontaktaufnahme</h2><p>Wenn Sie uns per E-Mail kontaktieren, werden Ihre Angaben zur Bearbeitung Ihrer Anfrage gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.</p><h2>Ihre Rechte</h2><p>Sie haben das Recht auf Auskunft, Berichtigung, Löschung und Einschränkung der Verarbeitung Ihrer personenbezogenen Daten. Wenden Sie sich an die oben genannte Adresse.</p>',
 8),
('404',
 'Seite nicht gefunden',
 'Seite nicht gefunden | Rothe-Transporte',
 'Diese Seite existiert nicht oder wurde verschoben.',
 'Diese Strecke führt ins Leere.',
 'Die gesuchte Seite gibt es nicht (mehr). Vielleicht hilft Ihnen die Navigation oben weiter.',
 '<p>Falls Sie etwas Bestimmtes suchen, rufen Sie uns einfach an: <a href="tel:+497127182310">07127 18231</a>.</p>',
 99);

-- ── Vehicles (technische Daten UNVERAENDERT) ─────────────────────────────────
INSERT INTO vehicles (slug, name, marketing_text, length_m, width_m, height_m, payload_kg, euro_pallets, axles, special_features, sort_order) VALUES
('tieflader-sattelauflieger',
 'Tieflader-Sattelauflieger',
 'Unser Spezialist für sperrige und voluminöse Maschinen. Die niedrige Ladehöhe macht ihn flexibel einsetzbar – auch dort, wo andere Fahrzeuge an der Höhe scheitern. Bis 28 Tonnen Nutzlast und 33 Europaletten.',
 13.60, 2.48, 3.70, 28000, 33, 3,
 'Niedrige Ladehöhe; ideal für sperrige und voluminöse Güter',
 1),
('tautliner-sattelzug',
 'Tautliner-Sattelzug',
 'Standardisierte, palettierte und verpackte Ware bewegt unser Tautliner schnell und wettergeschützt. Die beidseitig öffnende Schiebeplane erlaubt komfortables Be- und Entladen – auch unter Zeitdruck.',
 13.60, 2.48, 2.70, 25000, 33, 3,
 'Beidseitig öffnende Schiebeplane; standardisierte, verpackte Güter',
 2),
('anhaenger-alltagsheld',
 'Anhänger „Alltagsheld"',
 'Klein, aber präzise: für kompakte, leichte und palettierte Güter. Die integrierte Auffahrrampe erlaubt ebenerdiges Be- und Entladen, die Lenkachse macht ihn auch in engen Höfen wendig.',
 NULL, NULL, NULL, NULL, NULL, 2,
 'Integrierte Auffahrrampe; Lenkachse; ebenerdiges Beladen',
 3),
('motorwagen-mit-ladekran',
 'Motorwagen mit Ladekran',
 'Wenn der Stapler vor Ort fehlt: unser Motorwagen mit Ladekran und Lenkachse setzt Maschinen punktgenau ab – auch auf engen Baustellen und in Innenstädten.',
 NULL, NULL, NULL, NULL, NULL, 3,
 'Ladekran; Lenkachse; für enge Baustellen und Stadtbereiche',
 4);

-- ── Services ──────────────────────────────────────────────────────────────────
INSERT INTO services (slug, title, summary, body_html, icon_key, sort_order) VALUES
('maschinentransporte',
 'Maschinentransporte',
 'Spezialisiert auf Werkzeugmaschinen, Anlagen und industrielle Großteile.',
 '<p>Maschinentransporte sind unser Kerngeschäft seit 2005. Wir transportieren Werkzeugmaschinen, Anlagenkomponenten und industrielle Großteile mit dem passenden Fahrzeug, der richtigen Ladungssicherung und festen Fahrern, die wissen, worauf es ankommt.</p>',
 'truck',
 1),
('spezialtransporte',
 'Spezialtransporte',
 'Sperriges, voluminöses oder hohes Frachtgut – mit Tieflader und Erfahrung.',
 '<p>Wo Standardmaße nicht reichen, kommt unser Tieflader-Sattelauflieger zum Einsatz. Niedrige Ladehöhe, 28 Tonnen Nutzlast, flexibles Ladevolumen – die Lösung für Ware, die anderswo nicht passt.</p>',
 'tieflader',
 2),
('lagerung',
 'Lagerung & Kommissionierung',
 'Eigene Lagerhallen für Großteile, Regal- und Palettenware.',
 '<p>Wir lagern Großteile, Regalware und palettierte Industriegüter in eigenen Hallen. Kurze Wege zwischen Lager und Fuhrpark sparen Zeit – Ihre Sendung steht zur Abholung bereit, wenn der Lkw vorfährt.</p>',
 'warehouse',
 3),
('stapler-entladedienst',
 'Stapler- & Entladedienst',
 'Be- und Entladung bis 3,5 t direkt vor Ort.',
 '<p>Wenn am Lade- oder Entladeort kein Stapler verfügbar ist, übernehmen wir das selbst – mit eigenem Gerät bis 3,5 Tonnen. Ein Anruf genügt, der Rest ist eingespielt.</p>',
 'forklift',
 4);

-- ── Timeline events ───────────────────────────────────────────────────────────
INSERT INTO timeline_events (year, title, description, sort_order) VALUES
(1978, 'Gründung in Münsingen', 'Karl-Otto Rothe gründet das Transportunternehmen als Ein-Mann-Betrieb.', 1),
(1985, 'Umzug nach Walddorfhaeslach', 'Verlagerung des Standorts in den Landkreis Reutlingen.', 2),
(1991, 'Erweiterung des Fuhrparks', 'Anschaffung weiterer Fahrzeuge zur Bewältigung steigender Nachfrage.', 3),
(2005, 'Spezialisierung Maschinentransport', 'Ausrichtung auf Maschinen- und Anlagentransporte.', 4),
(2010, 'Zweite Generation', 'Christopher Rothe steigt ein und führt das Unternehmen mit.', 5),
(2015, 'Spezialanhänger', 'Erweiterung der Flotte um Tieflader-Sattelauflieger und Spezialanhänger.', 6),
(2018, 'Ausbildungsbetrieb', 'Anerkennung als Ausbildungsbetrieb für Berufskraftfahrer.', 7);
